d<-read.table('test.rhy_f0_file.csv', header=T, fileEncoding='UTF-8', sep=',',
	colClasses=c(ACC_dgm='numeric',
		ACC_dlm='numeric',
		ACC_mae='numeric',
		ACC_prop='numeric',
		ACC_rate='numeric',
		ci='factor',
		dur='numeric',
		f_max='numeric',
		fi='factor',
		grp_dialog='factor',
		grp_spk='factor',
		grp_turn='factor',
		n_peak='numeric',
		sm1='numeric',
		sm2='numeric',
		sm3='numeric',
		stm='factor'))
